### ISSUE TITLE
license

### ISSUE THREAD

**Issue by libyenter** [boedy/cordova-volume-control#1]
Hello, 

Is this plugin under MIT or any kind of license?

Can I use it in my App?

BTW, did you use any private API could cause problem by App store approving?

Thank you.

**Comment by boedy** [comment]
Hi @libyenter,

Feel free to use this plugin in your app. I don't imagine you will have any problems getting your app approved using this plugin.

I have to mention I developed this plugin without any prior iOS coding experience. I've not yet been able to test this plugin extensively as I'm currently not using this plugin in any project. The plugin is only a couple of lines, so I imagine you'll be able to make adjustments to it quite easily.
